# Generated by Django 5.0.6 on 2024-07-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=50)),
                ('Cisco_id', models.CharField(max_length=50)),
                ('Ticket_description', models.CharField(max_length=200)),
                ('OS_type', models.CharField(max_length=10)),
                ('Tool', models.CharField(max_length=10)),
                ('Ticket_State', models.CharField(max_length=50)),
            ],
        ),
    ]
